application: quibble
version: 1-0-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:
 
- url: /css
  static_dir: css

- url: /res
  static_dir: js

- url: /yui
  static_dir: yui
  
- url: /files
  static_dir: files

- url: /images
  static_dir: images
  
- url: /js
  static_dir: js

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
